services:
  - type: web
    name: onlyseries-towatch
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && ls -la dist/spa/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TMDB_API_KEY
        sync: false
      - key: OMDB_API_KEY_1
        sync: false
      - key: OMDB_API_KEY_2
        sync: false
      - key: OMDB_API_KEY_3
        sync: false
      - key: OMDB_API_KEY_4
        sync: false
      - key: OMDB_API_KEY_5
        sync: false
    healthCheckPath: /health
    healthCheckInterval: 30
